export const USER_CONSTANTS = {
  AUTH_LOGIN : "AUTH_LOGIN",
  AUTH_REGISTER : "AUTH_REGISTER",
  SET_USER_DETAILS : "SET_USER_DETAILS",
  COMMIT_USER_LOCAL : "COMMIT_USER_LOCAL",
  USER_LOGOUT : "USER_LOGOUT",
  INITIALIZE_USER: "INITIALIZE_USER"
}

export const CLASS_CONSTANTS = {
  QUIZ_QUESTIONS: "QUIZ_QUESTIONS",
  USER_CURRENT_CLASS: "USER_CURRENT_CLASS",
  ISWRONG_CLASS: "ISWRONG_CLASS",
  SET_PREVIOUS_CLASS: "SET_PREVIOUS_CLASS"
}

export const ADMIN_CONSTANTS = {
  SET_CLASSES: "SET_CLASSES",
  SET_DETAILED_CLASSES: "SET_DETAILED_CLASSES",
  SET_ADMIN_USER_DETAILS : "SET_ADMIN_USER_DETAILS",
  COMMIT_ADMIN_USER_LOCAL : "COMMIT_ADMIN_USER_LOCAL",
  ADMIN_USER_LOGOUT : "ADMIN_USER_LOGOUT",
  INITIALIZE_ADMIN_USER: "INITIALIZE_ADMIN_USER"
}